"""Add query_connections table

Revision ID: 2054decf4bf5
Revises: eb12c011eceb
Create Date: 2026-04-17 13:02:06.591188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2054decf4bf5'
down_revision: Union[str, Sequence[str], None] = 'eb12c011eceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_connections',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['db_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id', 'connection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_connections')
    # ### end Alembic commands ###
