"""update_chat_session

Revision ID: 73b4533e59d4
Revises: e21234e5ea0c
Create Date: 2026-04-01 11:06:42.975171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b4533e59d4'
down_revision: Union[str, Sequence[str], None] = 'e21234e5ea0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add tenant_id as nullable
    op.add_column('chat_sessions', sa.Column('tenant_id', sa.UUID(), nullable=True))
    
    # 2. Populate tenant_id from users table
    op.execute(
        """
        UPDATE chat_sessions
        SET tenant_id = users.tenant_id
        FROM users
        WHERE chat_sessions.user_id = users.id
        """
    )
    
    # 3. Clean up orphans that somehow didn't get a tenant_id
    op.execute("DELETE FROM chat_sessions WHERE tenant_id IS NULL")
    
    # 4. Enforce NOT NULL on tenant_id
    op.alter_column('chat_sessions', 'tenant_id', nullable=False)
    
    # 5. Clean up any globally shared sessions before enforcing constraint
    op.execute("DELETE FROM chat_sessions WHERE connection_id IS NULL")
    
    op.alter_column('chat_sessions', 'connection_id',
               existing_type=sa.UUID(),
               nullable=False)
               
    op.drop_constraint('uq_user_connection_session', 'chat_sessions', type_='unique')
    op.create_index('ix_chat_sessions_tenant_connection', 'chat_sessions', ['tenant_id', 'connection_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_chat_sessions_tenant_id_tenants', 'chat_sessions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_tenant_connection', table_name='chat_sessions')
    op.create_unique_constraint('uq_user_connection_session', 'chat_sessions', ['user_id', 'connection_id'])
    op.alter_column('chat_sessions', 'connection_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('chat_sessions', 'tenant_id')
    # ### end Alembic commands ###
