"""add_tenant_embeddings_and_backfill

Revision ID: a0356042768e
Revises: 2026_04_20_col_embeddings
Create Date: 2026-04-24 15:57:30.151047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0356042768e'
down_revision: Union[str, Sequence[str], None] = '2026_04_20_col_embeddings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('metric', 'cache', 'entity', 'relationship')", name='ck_tenant_embeddings_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_id', 'type', 'key', name='uq_tenant_source_type_key')
    )
    op.create_index('idx_tenant_embeddings_cache_hnsw', 'tenant_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where="type = 'cache' AND embedding IS NOT NULL")
    op.create_index('idx_tenant_embeddings_lookup', 'tenant_embeddings', ['tenant_id', 'source_id', 'type'], unique=False)
    op.create_index('idx_tenant_embeddings_metric_hnsw', 'tenant_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where="type = 'metric' AND embedding IS NOT NULL")
    op.alter_column('queries', 'generated_sql',
               existing_type=sa.TEXT(),
               nullable=False)
    # 1. Clean up orphaned records
    op.execute("DELETE FROM table_metadata_store WHERE connection_id NOT IN (SELECT id FROM db_connections)")
    
    # 2. Add column as nullable
    op.add_column('table_metadata_store', sa.Column('tenant_id', sa.UUID(), nullable=True))
    
    # 3. Backfill data
    op.execute("UPDATE table_metadata_store SET tenant_id = dc.tenant_id FROM db_connections dc WHERE table_metadata_store.connection_id = dc.id")
    
    # 4. Alter column to not null
    op.alter_column('table_metadata_store', 'tenant_id', existing_type=sa.UUID(), nullable=False)

    op.drop_constraint('uq_connection_schema_table', 'table_metadata_store', type_='unique')
    op.create_index('idx_table_metadata_tenant_conn', 'table_metadata_store', ['tenant_id', 'connection_id'], unique=False)
    op.create_index(op.f('ix_table_metadata_store_tenant_id'), 'table_metadata_store', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_tenant_connection_schema_table', 'table_metadata_store', ['tenant_id', 'connection_id', 'schema_name', 'table_name'])
    op.create_foreign_key(None, 'table_metadata_store', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_metadata_store', type_='foreignkey')
    op.drop_constraint('uq_tenant_connection_schema_table', 'table_metadata_store', type_='unique')
    op.drop_index(op.f('ix_table_metadata_store_tenant_id'), table_name='table_metadata_store')
    op.drop_index('idx_table_metadata_tenant_conn', table_name='table_metadata_store')
    op.create_unique_constraint('uq_connection_schema_table', 'table_metadata_store', ['connection_id', 'schema_name', 'table_name'])
    op.drop_column('table_metadata_store', 'tenant_id')
    op.alter_column('queries', 'generated_sql',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_tenant_embeddings_metric_hnsw', table_name='tenant_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where="type = 'metric' AND embedding IS NOT NULL")
    op.drop_index('idx_tenant_embeddings_lookup', table_name='tenant_embeddings')
    op.drop_index('idx_tenant_embeddings_cache_hnsw', table_name='tenant_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where="type = 'cache' AND embedding IS NOT NULL")
    op.drop_table('tenant_embeddings')
    # ### end Alembic commands ###
