"""Enhance saved queries traceability

Revision ID: a4b16ff0c230
Revises: d167581d8520
Create Date: 2026-04-07 15:56:31.897001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b16ff0c230'
down_revision: Union[str, Sequence[str], None] = 'd167581d8520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Avoid NOT NULL constraint failures by clearing existing saved queries and reports (dev environment)
    op.execute("DELETE FROM reports")
    op.execute("DELETE FROM saved_queries")

    # Rename existing columns to preserve data types and constraints instead of dropping
    op.alter_column('saved_queries', 'query_name', new_column_name='title')
    op.alter_column('saved_queries', 'generated_sql', new_column_name='query')

    op.add_column('saved_queries', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('saved_queries', sa.Column('username', sa.String(), nullable=False))
    op.add_column('saved_queries', sa.Column('database_name', sa.String(), nullable=False))

    op.create_index(op.f('ix_saved_queries_tenant_id'), 'saved_queries', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'saved_queries', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_queries', type_='foreignkey')
    op.drop_index(op.f('ix_saved_queries_tenant_id'), table_name='saved_queries')
    op.drop_column('saved_queries', 'database_name')
    op.drop_column('saved_queries', 'username')
    op.drop_column('saved_queries', 'tenant_id')
    op.alter_column('saved_queries', 'query', new_column_name='generated_sql')
    op.alter_column('saved_queries', 'title', new_column_name='query_name')
    # ### end Alembic commands ###
