"""Add multitenant and pgvector

Revision ID: e21234e5ea0c
Revises: a686ad554e50
Create Date: 2026-03-31 15:40:31.006978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e21234e5ea0c'
down_revision: Union[str, Sequence[str], None] = 'a686ad554e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_tenant_id'), 'knowledge_base_documents', ['tenant_id'], unique=False)
    op.create_table('knowledge_base_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_base_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_chunks_document_id'), 'knowledge_base_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_chunks_tenant_id'), 'knowledge_base_chunks', ['tenant_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('knowledge_base_enabled', sa.Boolean(), nullable=True))
    op.alter_column('chat_sessions', 'connection_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('db_connections', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_db_connections_tenant_id'), 'db_connections', ['tenant_id'], unique=False)
    op.drop_constraint('db_connections_user_id_fkey', 'db_connections', type_='foreignkey')
    op.create_foreign_key(None, 'db_connections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('db_connections', 'user_id')
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=True))

    # Data migration: Set a default tenant for existing users and connections
    op.execute("INSERT INTO tenants (id, name, is_active) VALUES ('00000000-0000-0000-0000-000000000000', 'Default Tenant', true) ON CONFLICT DO NOTHING")
    op.execute("UPDATE users SET tenant_id = '00000000-0000-0000-0000-000000000000' WHERE tenant_id IS NULL")
    op.execute("UPDATE db_connections SET tenant_id = '00000000-0000-0000-0000-000000000000' WHERE tenant_id IS NULL")

    op.alter_column('users', 'tenant_id', nullable=False)
    op.alter_column('db_connections', 'tenant_id', nullable=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.add_column('db_connections', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'db_connections', type_='foreignkey')
    op.create_foreign_key('db_connections_user_id_fkey', 'db_connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_db_connections_tenant_id'), table_name='db_connections')
    op.drop_column('db_connections', 'tenant_id')
    op.alter_column('chat_sessions', 'connection_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chat_sessions', 'knowledge_base_enabled')
    op.drop_index(op.f('ix_knowledge_base_chunks_tenant_id'), table_name='knowledge_base_chunks')
    op.drop_index(op.f('ix_knowledge_base_chunks_document_id'), table_name='knowledge_base_chunks')
    op.drop_table('knowledge_base_chunks')
    op.drop_index(op.f('ix_knowledge_base_documents_tenant_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    op.drop_table('tenants')
    # ### end Alembic commands ###
