"""Split saved_queries into queries and query_executions

Revision ID: f08e990a79bf
Revises: d5e6f7a8b9c0
Create Date: 2026-04-16 13:51:06.694771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f08e990a79bf'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_tenant_id'), 'queries', ['tenant_id'], unique=False)
    op.create_table('query_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_table_metadata_embedding', table_name='table_metadata_store', postgresql_using='hnsw')
    op.drop_index('ix_table_metadata_store_connection_id', table_name='table_metadata_store')
    op.drop_table('table_metadata_store')

    # Drop constraints FIRST
    op.add_column('dashboard_widgets', sa.Column('query_id', sa.UUID(), nullable=True))
    op.drop_constraint('dashboard_widgets_saved_query_id_fkey', 'dashboard_widgets', type_='foreignkey')
    op.drop_column('dashboard_widgets', 'saved_query_id')

    op.add_column('reports', sa.Column('query_id', sa.UUID(), nullable=True))
    op.drop_constraint('reports_saved_query_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'saved_query_id')

    op.drop_index('ix_saved_queries_tenant_id', table_name='saved_queries')
    op.drop_table('saved_queries')

    op.create_foreign_key(None, 'dashboard_widgets', 'queries', ['query_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_db_connections_status', table_name='db_connections')
    op.create_foreign_key(None, 'reports', 'queries', ['query_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_users_status', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.add_column('reports', sa.Column('saved_query_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_saved_query_id_fkey', 'reports', 'saved_queries', ['saved_query_id'], ['id'], ondelete='SET NULL')
    op.drop_column('reports', 'query_id')
    op.create_index('ix_db_connections_status', 'db_connections', ['status'], unique=False)
    op.add_column('dashboard_widgets', sa.Column('saved_query_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dashboard_widgets', type_='foreignkey')
    op.create_foreign_key('dashboard_widgets_saved_query_id_fkey', 'dashboard_widgets', 'saved_queries', ['saved_query_id'], ['id'], ondelete='SET NULL')
    op.drop_column('dashboard_widgets', 'query_id')
    op.create_table('saved_queries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('natural_language_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('query_result_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('database_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['db_connections.id'], name='saved_queries_connection_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='saved_queries_tenant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_queries_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='saved_queries_pkey')
    )
    op.create_index('ix_saved_queries_tenant_id', 'saved_queries', ['tenant_id'], unique=False)
    op.create_table('table_metadata_store',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), server_default=sa.text("'public'::character varying"), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('synonyms', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['db_connections.id'], name='table_metadata_store_connection_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='table_metadata_store_pkey'),
    sa.UniqueConstraint('connection_id', 'schema_name', 'table_name', name='uq_connection_schema_table')
    )
    op.create_index('ix_table_metadata_store_connection_id', 'table_metadata_store', ['connection_id'], unique=False)
    op.create_index('idx_table_metadata_embedding', 'table_metadata_store', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_table('query_executions')
    op.drop_index(op.f('ix_queries_tenant_id'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
